### ISSUE TITLE
运行示例错误

### ISSUE THREAD

**Issue by SC-Duan** [YuanmingZhang65/FastBiCmrMLM#3]
老师您好，
我运行自己的数据或者示例数据都出现报错：
Extracting number of samples and rownames from gen_sample.fam...
Extracting number of variants and colnames from gen_sample.bim...
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': input= must be a single character string containing a file name, a system command containing at least one space, a URL starting 'http[s]://', 'ftp[s]://' or 'file://', or, the input data itself containing at least one \n or \r
Calls: FastBiCmrMLM -> GmrMLM_single_env023 -> as.matrix -> fread
Execution halted
请问是什么原因呢？谢谢！

library("FastBiCmrMLM")
FastBiCmrMLM(fileGen="/home/soft/FastBiCmrMLM/extdata/gen_sample",
filePhe="/home/soft/FastBiCmrMLM/extdata/binary.csv",
fileGRM=NULL,filePS=NULL,PopStrType="PCA",
fileOut="/home/soft/FastBiCmrMLM/extdata/out/",
method="FastBiCmrMLM",trait=1)

加上下边的参数也一样报错。
#,SearchRadius=1e+6,svpal=1e-5,LODThreshold=3,CutToBinary=NULL,SubforGRM=FALSE,ChunkNum=5e+4,fastSPA=FALSE)

**Comment by YuanmingZhang65** [comment]
把主成分文件输入加进去，就不会报错了。目前的版本没有处理群体结构为空的情况，正在添加




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月24日(周一) 下午3:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [YuanmingZhang65/FastBiCmrMLM] 运行示例错误 (Issue #3)




 
老师您好，
 我运行自己的数据或者示例数据都出现报错：
 Extracting number of samples and rownames from gen_sample.fam...
 Extracting number of variants and colnames from gen_sample.bim...
 Error in h(simpleError(msg, call)) :
 error in evaluating the argument 'x' in selecting a method for function 'as.matrix': input= must be a single character string containing a file name, a system command containing at least one space, a URL starting 'http[s]://', 'ftp[s]://' or 'file://', or, the input data itself containing at least one \n or \r
 Calls: FastBiCmrMLM -&gt; GmrMLM_single_env023 -&gt; as.matrix -&gt; fread
 Execution halted
 请问是什么原因呢？谢谢！
 
library("FastBiCmrMLM")
 FastBiCmrMLM(fileGen="/home/soft/FastBiCmrMLM/extdata/gen_sample",
 filePhe="/home/soft/FastBiCmrMLM/extdata/binary.csv",
 fileGRM=NULL,filePS=NULL,PopStrType="PCA",
 fileOut="/home/soft/FastBiCmrMLM/extdata/out/",
 method="FastBiCmrMLM",trait=1)
 
加上下边的参数也一样报错。
 #,SearchRadius=1e+6,svpal=1e-5,LODThreshold=3,CutToBinary=NULL,SubforGRM=FALSE,ChunkNum=5e+4,fastSPA=FALSE)

**Comment by SC-Duan** [comment]
好的，谢谢您！

**Comment by SC-Duan** [comment]
老师您好，
我加了pca数据，然后测试没问题了。
但是我使用我的数据用相同的脚本计算的时候，出现错误：
Extracting number of samples and rownames from lj.SNP.filter.fam...
Extracting number of variants and colnames from lj.SNP.filter.bim...
Error in while (any(tau < 0)) { : missing value where TRUE/FALSE needed
Calls: FastBiCmrMLM -> GmrMLM_single_env023
Execution halted
请问潜在的问题是什么呢？我检查了我的数据，与测试数据是一致的。
谢谢！

**Comment by YuanmingZhang65** [comment]
今天我们上传了新版本软件，你的问题己经解决了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月26日(周三) 晚上8:00
收件人: ***@***.***&gt;;
抄送: "Yuan-Ming ***@***.******@***.***&gt;;
主题: Re: [YuanmingZhang65/FastBiCmrMLM] 运行示例错误 (Issue #3)




 
老师您好，
 我加了pca数据，然后测试没问题了。
 但是我使用我的数据用相同的脚本计算的时候，出现错误：
 Extracting number of samples and rownames from lj.SNP.filter.fam...
 Extracting number of variants and colnames from lj.SNP.filter.bim...
 Error in while (any(tau < 0)) { : missing value where TRUE/FALSE needed
 Calls: FastBiCmrMLM -&gt; GmrMLM_single_env023
 Execution halted
 请问潜在的问题是什么呢？我检查了我的数据，与测试数据是一致的。
 谢谢！
